# yaml-language-server: $schema=../node_modules/somod-schema/schemas/serverless-template/index.json

Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    SOMOD::Output:
      default: true # returns the table name
      attributes:
        - Arn # returns the ARN of the table
    Properties:
      # The properties are defined in AWS CloudFormation Reference at
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html
      TableName:
        SOMOD::ResourceName: User # SOMOD keyword which generates a unique table name during deployment
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: "userId"
          KeyType: "HASH"
      AttributeDefinitions:
        - AttributeName: "userId"
          AttributeType: "S"

  UserAPILambda:
    Type: AWS::Serverless::Function
    # The properties are defined in AWS SAM Reference at
    # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri:
        # With SOMOD::Function keyword, the lambda function code is automatically bundled from the mentioned function name.
        SOMOD::Function:
          name: userApi
      Environment:
        Variables:
          TABLE_NAME:
            SOMOD::Ref:
              resource: UserTable # Refer the default return value of the UserTable
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Resource:
                - SOMOD::Ref: # Refer the Arn Attribute of the UserTable
                    resource: UserTable
                    attribute: Arn
              Action:
                - "dynamodb:PutItem"
                - "dynamodb:Query"
                - "dynamodb:UpdateItem"
                - "dynamodb:DeleteItem"
                - "dynamodb:Scan"
      Events:
        Create:
          Type: HttpApi
          Properties:
            Method: POST
            Path: /user
            ApiId:
              SOMOD::Ref: # Refer to BaseHttpApi resource provided by the dependent module somod-http-api-gateway
                resource: BaseHttpApi
                module: somod-http-api-gateway
        Read:
          Type: HttpApi
          Properties:
            Method: GET
            Path: /user/{id}
            ApiId:
              SOMOD::Ref:
                resource: BaseHttpApi
                module: somod-http-api-gateway
        Update:
          Type: HttpApi
          Properties:
            Method: PUT
            Path: /user/{id}
            ApiId:
              SOMOD::Ref:
                resource: BaseHttpApi
                module: somod-http-api-gateway
        Delete:
          Type: HttpApi
          Properties:
            Method: DELETE
            Path: /user/{id}
            ApiId:
              SOMOD::Ref:
                resource: BaseHttpApi
                module: somod-http-api-gateway
        List:
          Type: HttpApi
          Properties:
            Method: GET
            Path: /user/list
            ApiId:
              SOMOD::Ref:
                resource: BaseHttpApi
                module: somod-http-api-gateway
